### ISSUE TITLE
Having troubles setting up kevm

### ISSUE THREAD

**Issue by Freak-w** [kframework/evm-semantics#111]
It's the first time I am using the k-framework. What I tried so far:
- downloaded and extracted k-distribution-4.0.0.zip from here: https://github.com/kframework/k/releases/tag/v4.0.0
- added the bin directory of k to the PATH variable in .bashrc
- set K_VERSION=uiuck in .bashrc
- clone the evm-semantics repo including submodules in a different directory

When I try to run ./Build I get the following error:
```
== Using uiuck
WARNING: pandoc-tangle not installed. Ignoring changes in markdown files

== kompile: .build/uiuck/ethereum-kompiled/extras/timestamp
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Could not find module: STRING-BUFFER
	Source(/home/foo/evm-semantics/./.build/uiuck/data.k)
	Location(16,5,16,25)
	at org.kframework.utils.errorsystem.KExceptionManager.create(KExceptionManager.java:170)
	at org.kframework.utils.errorsystem.KExceptionManager.compilerError(KExceptionManager.java:84)
	at org.kframework.kore.convertors.KILtoKORE.lambda$apply$152(KILtoKORE.java:140)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.kframework.kore.convertors.KILtoKORE.apply(KILtoKORE.java:141)
	at org.kframework.kore.convertors.KILtoKORE.apply(KILtoKORE.java:96)
	at org.kframework.parser.concrete2kore.ParserUtils.lambda$loadModules$24(ParserUtils.java:191)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.kframework.parser.concrete2kore.ParserUtils.loadModules(ParserUtils.java:191)
	at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:222)
	at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:206)
	at org.kframework.kompile.DefinitionParsing.parseDefinition(DefinitionParsing.java:154)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:139)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:128)
	at org.kframework.kompile.Kompile.run(Kompile.java:114)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:110)
	at org.kframework.main.Main.runApplication(Main.java:100)
	at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Could not find module: STRING-BUFFER
	Source(/home/foo/evm-semantics/./.build/uiuck/data.k)
	Location(16,5,16,25)
Makefile:109: recipe for target '.build/uiuck/ethereum-kompiled/extras/timestamp' failed
make: *** [.build/uiuck/ethereum-kompiled/extras/timestamp] Error 113
```

I have no idea what I might have missed during the setup. Does the evm-semantics directory belong (in a specific folder) inside the k-framework? Any help is appreciated!

**Comment by nishantjr** [comment]
Unfortunately, there's no github release of the version of `k` we're using. You could either download an install `k` from github, or use our CI scripts to set up k:

```
$ cd evm-semantics
$ ./tests/ci/with-k uiuck bash          # Open a shell with K downloaded, built and in PATH
$ ./Build run tests/VMTests/vmArithmeticTest/add0.json
```

**Comment by dwightguth** [comment]
The installation process has changed considerably since this issue was opened, so I'm going to close this. If you try to install it again and have more difficulties feel free to reopen this.
