### ISSUE TITLE
"Could not find main module with name ETHEREUM-SIMULATION in definition."

### ISSUE THREAD

**Issue by pirapira** [kframework/evm-semantics#120]
When I try to follow `README.md`, I hit the following error:
```
$ ./tests/ci/with-k rvk   ./Build run tests/VMTests/vmArithmeticTest/add0.json
<snip>
== Using rvk
== kompile: .build/rvk/driver-kompiled/interpreter
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Could not find main module with name ETHEREUM-SIMULATION in definition. Use --main-module to specify one.
 at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:113)
 at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:75)
 at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:234)
 at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:213)
 at org.kframework.kompile.DefinitionParsing.parseDefinition(DefinitionParsing.java:169)
 at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:149)
 at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:135)
 at org.kframework.kompile.Kompile.run(Kompile.java:121)
 at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:69)
 at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
 at org.kframework.main.Main.runApplication(Main.java:113)
 at org.kframework.main.Main.runApplication(Main.java:103)
 at org.kframework.main.Main.main(Main.java:52)
[Error] Compiler: Could not find main module with name ETHEREUM-SIMULATION in
definition. Use --main-module to specify one.
Makefile:119: recipe for target '.build/rvk/driver-kompiled/interpreter' failed
make: *** [.build/rvk/driver-kompiled/interpreter] Error 113
```

I'm on evm-semantics 176f6f5e79e0b5a8f71daa9b8632c7360b163c31.

**Comment by pirapira** [comment]
@ehildenb told me that `with-k` has disappeared since then.  I'll try again.
