### ISSUE TITLE
wrong test paths in README.md

### ISSUE THREAD

**Issue by pirapira** [kframework/evm-semantics#121]
I'm trying to follow `README.md` and I see
```
$ ./tests/ci/with-k uiuck ./Build debug tests/VMTests/vmArithmeticTest/add0.json
== Using uiuck
== debugging: tests/VMTests/vmArithmeticTest/add0.json
org.kframework.utils.errorsystem.KEMException: [Error] Critical: Could not read from file /home/yh/src/evm-semantics/./tests/VMTests/vmArithmeticTest/add0.json
 at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:109)
 at org.kframework.utils.errorsystem.KEMException.criticalError(KEMException.java:34)
 at org.kframework.utils.file.FileUtil.readFromWorkingDirectory(FileUtil.java:311)
 at org.kframework.krun.KRun.parse(KRun.java:445)
 at org.kframework.krun.KRun.getUserConfigVarsMap(KRun.java:335)
 at org.kframework.krun.KRun.parseConfigVars(KRun.java:364)
 at org.kframework.krun.KRun.run(KRun.java:93)
 at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:67)
 at org.kframework.main.FrontEnd.main(FrontEnd.java:34)
 at org.kframework.main.Main.runApplication(Main.java:415)
 at org.kframework.main.Main.runApplication(Main.java:264)
 at org.kframework.main.Main.main(Main.java:73)
```

**Comment by pirapira** [comment]
adding `ethereum-tests` after `tests/` fixed the problem.  I'll file a PR.
