### ISSUE TITLE
make fails with [Error] Compiler: Could not find main module with name ETHEREUM-SIMULATION in definition

### ISSUE THREAD

**Issue by nud3l** [kframework/evm-semantics#250]
I am trying to get build the evm-semantics using the `make deps` and `make` commands.

`make deps` works out fine and `make` throws me this error:

```
== kompile: .build/ocaml/driver-kompiled/constants.cmx
eval $(opam config env) \
	&& /home/nud3l/apps/evm-semantics/.build/k/k-distribution/target/release/k/bin/kompile --debug --main-module ETHEREUM-SIMULATION \
					    --syntax-module ETHEREUM-SIMULATION .build/ocaml/driver.k --directory .build/ocaml \
					    --hook-namespaces "KRYPTO BLOCKCHAIN" --gen-ml-only -O3 --non-strict \
	&& cd .build/ocaml/driver-kompiled \
	&& ocamlfind opt -O3 -c -g constants.ml -package gmp -package zarith -safe-string
org.kframework.utils.errorsystem.KEMException: [Error] Compiler: Could not find main module with name ETHEREUM-SIMULATION in definition. Use --main-module to specify one.
	at org.kframework.utils.errorsystem.KEMException.create(KEMException.java:99)
	at org.kframework.utils.errorsystem.KEMException.compilerError(KEMException.java:61)
	at org.kframework.parser.concrete2kore.ParserUtils.getMainModule(ParserUtils.java:264)
	at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:246)
	at org.kframework.parser.concrete2kore.ParserUtils.loadDefinition(ParserUtils.java:226)
	at org.kframework.kompile.DefinitionParsing.parseDefinition(DefinitionParsing.java:178)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:148)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:123)
	at org.kframework.kompile.Kompile.run(Kompile.java:107)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:114)
	at org.kframework.main.Main.runApplication(Main.java:104)
	at org.kframework.main.Main.main(Main.java:53)
[Error] Compiler: Could not find main module with name ETHEREUM-SIMULATION in
definition. Use --main-module to specify one.
make: *** [Makefile:153: .build/ocaml/driver-kompiled/constants.cmx] Error 113
```

I am on Fedora 28 (4.17.14-202.fc28.x86_64) and I think I have installed all the required dependencies. At least `make deps` does not give me an error.

Any idea what is causing this?

**Comment by nud3l** [comment]
It seems like this has been caused by me.

When first running `make` I did not have pandoc installed. This caused `.build/ocaml/driver.k` to be empty. After installing pandoc `driver.k` remained empty.

`make clean` and then `make deps` and `make` resolved the issue.

**Comment by nud3l** [comment]
Issue resolved.
