### ISSUE TITLE
kevm debug add0.json from README fails with java.lang.NumberFormatException: For input string: "0x100"

### ISSUE THREAD

**Issue by gsalzer** [kframework/evm-semantics#269]
I have installed kevm according to the instructions in the README on Ubuntu 18.04 and succeeded in running the first few example commands. Debugging, however, raises an exception.
Any suggestions?

```
$ ./kevm debug tests/ethereum-tests/VMTests/vmArithmeticTest/add0.json
== debugging: tests/ethereum-tests/VMTests/vmArithmeticTest/add0.json
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:233)
	at jline.UnixTerminal.<init>(UnixTerminal.java:64)
	at jline.UnixTerminal.<init>(UnixTerminal.java:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:209)
	at jline.TerminalFactory.create(TerminalFactory.java:100)
	at jline.TerminalFactory.get(TerminalFactory.java:184)
	at jline.TerminalFactory.get(TerminalFactory.java:190)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:240)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:232)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:220)
	at org.kframework.krun.modes.DebugMode.DebugExecutionMode.getConsoleReader(DebugExecutionMode.java:68)
	at org.kframework.krun.modes.DebugMode.DebugExecutionMode.execute(DebugExecutionMode.java:93)
	at org.kframework.krun.KRun.run(KRun.java:87)
	at org.kframework.krun.KRunFrontEnd.run(KRunFrontEnd.java:92)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:52)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:107)
	at org.kframework.main.Main.main(Main.java:53)

KDebug> 

```

**Comment by ehildenb** [comment]
`--debugger` option shouldn't be trusted, it's being removed in #317.
