### ISSUE TITLE
Install KEVM problems (new)

### ISSUE THREAD

**Issue by ricky222368** [kframework/evm-semantics#646]
I use Ubuntu and follow the steps in README.md in evm-semantics folder, but have some problem.
In Building part, when I use command make build RELEASE=1 ,
I get some problems : 
```

/home/ricky/Desktop/evmmmm/evm-semantics/deps/k/k-distribution/target/release/k/bin/kompile --debug --main-module ETHEREUM-SIMULATION --backend llvm \
                 --syntax-module ETHEREUM-SIMULATION .build/defn/llvm/driver.k \
                 --directory .build/defn/llvm -I .build/defn/llvm -I .build/defn/llvm \
                 --hook-namespaces KRYPTO \
                  \
                 -ccopt /home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/plugin-c/crypto.cpp \
                 -ccopt /home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/plugin-c/blake2.cpp \
                 -ccopt -g -ccopt -std=c++14 -ccopt -O2 \
                 -ccopt -L/home/ricky/Desktop/evmmmm/evm-semantics/.build/local/lib \
                 -ccopt -lff -ccopt -lcryptopp -ccopt -lsecp256k1 -ccopt -lprocps
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.kframework.kompile.DefinitionParsing.resolveNonConfigBubbles(DefinitionParsing.java:280)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveNonConfigBubbles$7(DefinitionParsing.java:250)
	at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:74)
	at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:71)
	at org.kframework.definition.ModuleTransformer.apply(transformers.scala:67)
	at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:110)
	at org.kframework.kompile.DefinitionParsing.resolveNonConfigBubbles(DefinitionParsing.java:250)
	at org.kframework.kompile.DefinitionParsing.parseDefinitionAndResolveBubbles(DefinitionParsing.java:175)
	at org.kframework.kompile.Kompile.parseDefinition(Kompile.java:151)
	at org.kframework.kompile.Kompile.run(Kompile.java:125)
	at org.kframework.kompile.KompileFrontEnd.run(KompileFrontEnd.java:70)
	at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
	at org.kframework.main.Main.runApplication(Main.java:118)
	at org.kframework.main.Main.runApplication(Main.java:108)
	at org.kframework.main.Main.main(Main.java:56)
Caused by: java.lang.NullPointerException
	at org.kframework.parser.concrete2kore.disambiguation.TypeInferencer.computeStatus(TypeInferencer.java:748)
	at org.kframework.parser.concrete2kore.disambiguation.TypeInferencer.status(TypeInferencer.java:770)
	at org.kframework.parser.concrete2kore.disambiguation.TypeInferenceVisitor.apply(TypeInferenceVisitor.java:102)
	at org.kframework.parser.concrete2kore.ParseInModule.parseStringTerm(ParseInModule.java:230)
	at org.kframework.parser.concrete2kore.ParseInModule.parseString(ParseInModule.java:150)
	at org.kframework.kompile.DefinitionParsing.performParse(DefinitionParsing.java:420)
	at org.kframework.kompile.DefinitionParsing.lambda$resolveNonConfigBubbles$15(DefinitionParsing.java:278)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[Error] Internal: Uncaught exception thrown of type NullPointerException (null)
Makefile:282: recipe for target '.build/defn/llvm/driver-kompiled/interpreter' failed
make: *** [.build/defn/llvm/driver-kompiled/interpreter] Error 1

```

and when I do make install RELEASE=1 :
```
/home/ricky/Desktop/evmmmm/evm-semantics/deps/k/k-distribution/target/release/k/bin/kompile --debug --main-module EVM-NODE --backend llvm \
                 --syntax-module EVM-NODE /home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/node/evm-node.k \
                 --directory /home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/node -I /home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/node -I /home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/node \
                 --hook-namespaces "KRYPTO BLOCKCHAIN" \
                 --no-llvm-kompile \
                 
protoc --cpp_out=/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/node/evm-node-kompiled/plugin -I /home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/plugin /home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/plugin/proto/msg.proto
cd .build/defn/vm && cmake /home/ricky/Desktop/evmmmm/evm-semantics/cmake/node -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm
make[1]: Entering directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
make[2]: Entering directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
make[3]: Entering directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
Scanning dependencies of target kevm-vm
make[3]: Leaving directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
make[3]: Entering directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
[ 10%] Building CXX object CMakeFiles/kevm-vm.dir/home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/vm-c/main.cpp.o
[ 20%] Building CXX object CMakeFiles/kevm-vm.dir/home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/vm-c/vm.cpp.o
[ 30%] Building CXX object CMakeFiles/kevm-vm.dir/home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/plugin-c/blockchain.cpp.o
[ 40%] Building CXX object CMakeFiles/kevm-vm.dir/home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/plugin-c/world.cpp.o
[ 50%] Building CXX object CMakeFiles/kevm-vm.dir/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/node/evm-node-kompiled/plugin/proto/msg.pb.cc.o
[ 60%] Building CXX object CMakeFiles/kevm-vm.dir/home/ricky/Desktop/evmmmm/evm-semantics/deps/plugin/vm-c/kevm/semantics.cpp.o
[ 70%] Linking CXX executable kevm-vm
make[3]: Leaving directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
[100%] Built target kevm-vm
make[2]: Leaving directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
make[1]: Leaving directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
cd .build/defn/vm && make install
make[1]: Entering directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
make[2]: Entering directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
make[3]: Entering directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
make[3]: Leaving directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
[100%] Built target kevm-vm
make[2]: Leaving directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/bin/kevm-vm
-- Set runtime path of "/usr/local/bin/kevm-vm" to ""
make[1]: Leaving directory '/home/ricky/Desktop/evmmmm/evm-semantics/.build/defn/vm'
```

is it success?

where do I have fault ?
thanks for your help.

**Comment by ehildenb** [comment]
@ricky222368 are you still having this problem? I'm having trouble following your example above, did you first run `make deps RELEASE=1`? That needs to be run before `make build`.

Also, please use GitHub code blocks to format your code, it makes it much easier to read.

**Comment by ricky222368** [comment]
yes my ubuntu environment also has this problem.
I have already done `make deps RELEASE=1` , and success.
sorry for that, I'll improve it.
